apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartdocs-api
  namespace: smartdocs-agentic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartdocs-api
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
