"""This file contains the constants used in the project"""
from enum import Enum


class DatabaseStatus(str, Enum):
    """This class contains the status of the database"""
    INGESTING_DATA_SHEET_ADM = "INGESTING_DATA_SHEET_ADM"
    INGESTING_DATA_SHEET_ADM_SUCCESSFUL = "INGESTING_DATA_SHEET_ADM_SUCCESSFUL"
    INGESTING_DATA_SHEET_ADM_FAILED = "INGESTING_DATA_SHEET_ADM_FAILED"
    INGESTING_HMB = "INGESTING_HMB"
    INGESTING_HMB_SUCCESSFUL = "INGESTING_HMB_SUCCESSFUL"
    INGESTING_HMB_FAILED = "INGESTING_HMB_FAILED"
    GETTING_LIST_OF_DOCUMENTS = "GETTING_LIST_OF_DOCUMENTS"
    GETTING_LIST_OF_DOCUMENTS_SUCCESSFUL = "GETTING_LIST_OF_DOCUMENTS_SUCCESSFUL"
    GETTING_LIST_OF_DOCUMENTS_FAILED = "GETTING_LIST_OF_DOCUMENTS_FAILED"
    INGESTING_PROCESS_NARRATIVE_ADM = "INGESTING_PROCESS_NARRATIVE_ADM"
    INGESTING_PROCESS_NARRATIVE_ADM_SUCCESSFUL = (
        "INGESTING_PROCESS_NARRATIVE_ADM_SUCCESSFUL"
    )
    INGESTING_PROCESS_NARRATIVE_ADM_FAILED = "INGESTING_PROCESS_NARRATIVE_ADM_FAILED"
    INGESTING_CONTROL_NARRATIVE_ADM = "INGESTING_CONTROL_NARRATIVE_ADM"
    INGESTING_CONTROL_NARRATIVE_ADM_SUCCESSFUL = (
        "INGESTING_CONTROL_NARRATIVE_ADM_SUCCESSFUL"
    )
    INGESTING_CONTROL_NARRATIVE_ADM_FAILED = "INGESTING_CONTROL_NARRATIVE_ADM_FAILED"


class ADM_IngestionStatus(str, Enum):   # pylint: disable=invalid-name
    """This class contains the status of the ingestion process"""
    INGESTING = "INGESTING"
    INGESTION_COMPLETED = "INGESTION_COMPLETED"
