"""This file contains the actions that can be performed"""

from enum import Enum


class Actions(str, Enum):
    """This class contains the actions that can be performed"""

    INGEST_DATA_SHEET_ADM_INTO_NEO4J = "INGEST_DATA_SHEET_ADM_INTO_NEO4J"
    EXTRACT_CONTROL_NARRATIVE_DATA = "EXTRACT_CONTROL_NARRATIVE_DATA"
    EXTRACT_HMB_DATA = "EXTRACT_HMB_DATA"
    EXTRACT_PROCESS_NARRATIVE_DATA = "EXTRACT_PROCESS_NARRATIVE_DATA"
    EXTRACT_PROCESS_NARRATIVE_RAG_DATA = "EXTRACT_PROCESS_NARRATIVE_RAG_DATA"
    EXTRACT_PROCESS_NARRATIVE_RAG_JUNIOR_DATA = (
        "EXTRACT_PROCESS_NARRATIVE_RAG_JUNIOR_DATA"
    )
    EXTRACT_CONTROL_NARRATIVE_RAG_JUNIOR_DATA = (
        "EXTRACT_CONTROL_NARRATIVE_RAG_JUNIOR_DATA"
    )
    TRIGGERED_PROCESS_NARRATIVE_RAG_JUNIOR_DATA_ACTION = (
        "TRIGGERED_PROCESS_NARRATIVE_RAG_JUNIOR_DATA_ACTION"
    )
    TRIGGERED_DATA_SHEET_DATA_ACTION = "TRIGGERED_DATA_SHEET_DATA_ACTION"
    TRIGGERED_CONTROL_NARRATIVE_DATA_ACTION = "TRIGGERED_CONTROL_NARRATIVE_DATA_ACTION"
    EXTRACT_ASSET_NARRATIVE_DATA = "EXTRACT_ASSET_NARRATIVE_DATA"
    EXTRACT_DATA_SHEET_DATA = "EXTRACT_DATA_SHEET_DATA"
    EXTRACT_DATA_SHEET_DATA_V2 = "EXTRACT_DATA_SHEET_DATA_V2"
    INGEST_PFD_INTO_NEO4J = "INGEST_PFD_INTO_NEO4J"
    INGEST_HMB_INTO_NEO4J = "INGEST_HMB_INTO_NEO4J"
    GET_LIST_OF_DOCUMENTS = "GET_LIST_OF_DOCUMENTS"
    EXTRACT_HMB_DOCUMENT_DATA = "EXTRACT_HMB_DOCUMENT_DATA"
    INGEST_PROCESS_NARRATIVE_ADM_INTO_NEO4J = "INGEST_PROCESS_NARRATIVE_ADM_INTO_NEO4J"
    EXTRACT_CAUSE_AND_EFFECT_DATA = "EXTRACT_CAUSE_AND_EFFECT_DATA"
    INGEST_CONTROL_NARRATIVE_ADM_INTO_NEO4J = "INGEST_CONTROL_NARRATIVE_ADM_INTO_NEO4J"
    GET_DATA_SHEET_STANDARD_DETAILS = "GET_DATA_SHEET_STANDARD_DETAILS"
    CHECK_DOCUMENT_STATUS = "CHECK_DOCUMENT_STATUS"
