"""This file contains the extractions that can be performed"""

from enum import Enum


class Extractions(str, Enum):
    """Extraction Actions"""

    INITIAL_DATA_SHEET_EXTRACTION = "INITIAL_DATA_SHEET_EXTRACTION"
    DATA_SHEET_TABLE_EXTRACTION = "DATA_SHEET_TABLE_EXTRACTION"
    DATA_SHEET_SECOND_SHOT_TABLE_EXTRACTION = "DATA_SHEET_SECOND_SHOT_TABLE_EXTRACTION"
    DATA_SHEET_GENERATE_ADM = "DATA_SHEET_GENERATE_ADM"
    DATA_SHEET_GENERATE_RAW_JSON = "DATA_SHEET_GENERATE_RAW_JSON"
    DATA_SHEET_INDIVIDUAL_TABLE_EXTRACTION = "DATA_SHEET_INDIVIDUAL_TABLE_EXTRACTION"
    DATA_SHEET_STANDARD_TABLE_NAME = "DATA_SHEET_STANDARD_TABLE_NAME"
    DATA_SHEET_STANDARD_ASSET_CLASS_NAME = "DATA_SHEET_STANDARD_ASSET_CLASS_NAME"
    DATA_SHEET_INPUT_DATA_EXTRACTION = "DATA_SHEET_INPUT_DATA_EXTRACTION"
    PROCESS_NARRATIVE_STREAM_CONDITION_EXTRACTION = "PROCESS_NARRATIVE_STREAM_CONDITION_EXTRACTION"
    PROCESS_NARRATIVE_EQUIPMENT_OPERATING_CONDITION_EXTRACTION = (
        "PROCESS_NARRATIVE_EQUIPMENT_OPERATING_CONDITION_EXTRACTION"
    )
